CREATE TABLE product_review (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	product_review_id INT NOT NULL,
    review_rating INT NOT NULL,
    /* Date */
    year varchar(4) NOT NULL,
    quater varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    review_date TIMESTAMP NOT NULL, 

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date TIMESTAMP,
    product_sell_end_date TIMESTAMP,
    product_discontinued_date TIMESTAMP,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE bill_of_materials (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	bill_of_materials_id INT NOT NULL,
    bill_of_materials_bom_level INT NOT NULL,
    bill_of_materials_per_assembly_qty INT NOT NULL,
    bill_of_materials_unit_measure_code varchar(255),

    /* Date */
    start_date_year varchar(4) NOT NULL,
    start_date_quater varchar(1) NOT NULL,
    start_date_month varchar(2) NOT NULL,
    start_date_day varchar(2) NOT NULL,
    start_date_hour varchar(2) NOT NULL,
    start_date_minute varchar(2) NOT NULL,
    bill_of_materials_start_date TIMESTAMP,

     /* Date */
    end_date_year varchar(4) NOT NULL,
    end_date_quater varchar(1) NOT NULL,
    end_date_month varchar(2) NOT NULL,
    end_date_day varchar(2) NOT NULL,
    end_date_hour varchar(2) NOT NULL,
    end_date_minute varchar(2) NOT NULL,
    bill_of_materials_end_date TIMESTAMP,
    

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date TIMESTAMP,
    product_sell_end_date TIMESTAMP,
    product_discontinued_date TIMESTAMP,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE special_offer (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	special_offer_id INT NOT NULL,
    special_offer_discount_pct DECIMAL(19,4) NOT NULL,
    special_offer_min_qty INT NOT NULL,
    special_offer_max_qty INT NOT NULL,
    
    /* Date */
    start_date_year varchar(4) NOT NULL,
    start_date_quater varchar(1) NOT NULL,
    start_date_month varchar(2) NOT NULL,
    start_date_day varchar(2) NOT NULL,
    start_date_hour varchar(2) NOT NULL,
    start_date_minute varchar(2) NOT NULL,
    special_offer_start_date TIMESTAMP NOT NULL, 

    /* Date */
    end_date_year varchar(4) NOT NULL,
    end_date_quater varchar(1) NOT NULL,
    end_date_month varchar(2) NOT NULL,
    end_date_day varchar(2) NOT NULL,
    end_date_hour varchar(2) NOT NULL,
    end_date_minute varchar(2) NOT NULL,
    special_offer_end_date TIMESTAMP NOT NULL, 

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date TIMESTAMP,
    product_sell_end_date TIMESTAMP,
    product_discontinued_date TIMESTAMP,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE bonus (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    bonus_amount DECIMAL(19,4) NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quater varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    bonus_date TIMESTAMP NOT NULL,

    /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date TIMESTAMP,
    employee_birth_date TIMESTAMP,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date TIMESTAMP,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE employee_pay_history (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    business_entity_id INT NOT NULL,
    rate DECIMAL(19,4) NOT NULL,
    pay_frequency INT NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quater varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    rate_change_date TIMESTAMP NOT NULL,

     /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date TIMESTAMP,
    employee_birth_date TIMESTAMP,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date TIMESTAMP,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),
 
    change_date TIMESTAMP,
);

CREATE TABLE department_history(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    
    /* Date */
    year varchar(4) NOT NULL,
    quater varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    bonus_date TIMESTAMP NOT NULL,

    /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date TIMESTAMP,
    employee_birth_date TIMESTAMP,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date TIMESTAMP,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE employee_deparment_history (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,

    /* Shift */
    shift_id INT NOT NULL,
    shift_name varchar(255) NOT NULL,
    shift_start_time TIME NOT NULL,
    shift_end_time TIME NOT NULL,

    /* Department */
    department_id INT NOT NULL,
    department_group_name varchar(255) NOT NULL,
    department_name varchar(255) NOT NULL,
    
    /* Date */
    start_date_year varchar(4) NOT NULL,
    start_date_quater varchar(1) NOT NULL,
    start_date_month varchar(2) NOT NULL,
    start_date_day varchar(2) NOT NULL,
    start_date_hour varchar(2) NOT NULL,
    start_date_minute varchar(2) NOT NULL,
    start_date TIMESTAMP NOT NULL,

    /* Date */
    end_date_year varchar(4) NOT NULL,
    end_date_quater varchar(1) NOT NULL,
    end_date_month varchar(2) NOT NULL,
    end_date_day varchar(2) NOT NULL,
    end_date_hour varchar(2) NOT NULL,
    end_date_minute varchar(2) NOT NULL,
    end_date TIMESTAMP NOT NULL,

     /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date TIMESTAMP,
    employee_birth_date TIMESTAMP,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date TIMESTAMP,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE transaction_history (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    transaction_id INT NOT NULL,
    quantity INT NOT NULL,
    actual_cost DECIMAL(19,4) NOT NULL,

    /* Transaction Type */
    transaction_type varchar(1) NOT NULL,

    /* Forgein keys sales_order */
    sales_order_s_key INT NOT NULL,
    sales_order_id INT NOT NULL,
    sales_order_line_id varchar(255) NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quater varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date TIMESTAMP,
    product_sell_end_date TIMESTAMP,
    product_discontinued_date TIMESTAMP,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP,
    FOREIGN KEY (sales_order_s_key) references sales_order(s_key)
);

CREATE TABLE business_entity_contact (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,

    /* Contact Type */
    contact_type_id INT NOT NULL,
    contact_type_name varchar(255) NOT NULL,

    /* Vendor */
    vendor_id INT NOT NULL,
    vendor_account_number varchar(255) NOT NULL,
    vendor_name varchar(255) NOT NULL,
    vendor_purchasing_website varchar(max),
    vendor_credit_rating INT NOT NULL,
    vender_preferred_vendor_status varchar(max),
    vendor_active bit NOT NULL,

    /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date TIMESTAMP,
    employee_birth_date TIMESTAMP,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date TIMESTAMP,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),
    
    change_date TIMESTAMP,
);