CREATE TABLE product_review (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	product_review_id INT NOT NULL,
    review_rating INT NOT NULL,
    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    review_date date NOT NULL, 

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE bill_of_materials (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	bill_of_materials_id INT NOT NULL,
    bill_of_materials_bom_level INT NOT NULL,
    bill_of_materials_per_assembly_qty INT NOT NULL,
    bill_of_materials_unit_measure_code varchar(255),

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    bill_of_materials_start_date date,
    bill_of_materials_end_date date,
    

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE special_offer (
    s_key INT IDENTITY(1,1) PRIMARY KEY,
	special_offer_id INT NOT NULL,
    special_offer_discount_pct DECIMAL(19,4) NOT NULL,
    special_offer_min_qty INT NOT NULL,
    special_offer_max_qty INT NOT NULL,
    
    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    special_offer_start_date date NOT NULL, 
    special_offer_end_date date NOT NULL, 

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP NOT NULL
);

CREATE TABLE bonus (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    bonus_amount DECIMAL(19,4) NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    bonus_date date NOT NULL,

    /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE employee_pay_history (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    business_entity_id INT NOT NULL,
    rate DECIMAL(19,4) NOT NULL,
    pay_frequency INT NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    rate_change_date date NOT NULL,

     /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),
 
    change_date TIMESTAMP,
);

CREATE TABLE department_history(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    
    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    bonus_date date NOT NULL,

    /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE employee_pay_history1 (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,

    /* Shift */
    shift_id INT NOT NULL,
    shift_name varchar(255) NOT NULL,
    shift_start_time TIME NOT NULL,
    shift_end_time TIME NOT NULL,

    /* Department */
    department_id INT NOT NULL,
    department_group_name varchar(255) NOT NULL,
    department_name varchar(255) NOT NULL,
    
    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,

     /* Employee */
    employee_id INT NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    change_date TIMESTAMP,
);

CREATE TABLE transaction_history (
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    transaction_id INT NOT NULL,
    quantity INT NOT NULL,
    actual_cost DECIMAL(19,4) NOT NULL,

    /* Transaction Type */
    transaction_type varchar(1) NOT NULL,

    /* Forgein keys sales_order */
    sales_order_s_key INT NOT NULL,
    sales_order_id INT NOT NULL,
    sales_order_line_id varchar(255) NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    transaction_date date NOT NULL,

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_description varchar(max),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,
);

CREATE TABLE sales_territory_history(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    sales_territory_history_business_entity_id varchar(255) NOT NULL,
    sales_territory_history_territory_id INT NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    end_date date,

    start_date date NOT NULL,

    /* Employee */
    employee_id varchar(255) NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    /*sales_territory*/
    sales_territory_territory_id INT NOT NULL,
    sales_territory_country_region_code varchar(3) NOT NULL,
    sales_territory_group varchar(50) NOT NULL,
    sales_territory_name varchar(50) NOT NULL,
    sales_territory_sales_ytd DECIMAL(19,4) NOT NULL,
    sales_territory_sales_last_year DECIMAL(19,4) NOT NULL,
    sales_territory_cost_ytd DECIMAL(19,4) NOT NULL,
    sales_territory_cost_last_year DECIMAL(19,4) NOT NULL,

    /*country_region_customer*/
    country_region_currency_currency_code varchar(3) NOT NULL,
    country_region_currency_country_region_code varchar(3) NOT NULL,

    /*currency*/
    currency_code varchar(3) NOT NULL,
    currency_name varchar(255) NOT NULL,
 
    change_date TIMESTAMP,
);


CREATE TABLE sales_person_quota_history(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    sales_person_quota_history_business_entity_id varchar(255) NOT NULL,
    sales_quota DECIMAL(19,4) NOT NULL,
    
    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    quota_date date NOT NULL,

    /* Employee */
    employee_id varchar(255) NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    /*sales_territory*/
    sales_territory_territory_id INT NOT NULL,
    sales_territory_country_region_code varchar(3) NOT NULL,
    sales_territory_group varchar(50) NOT NULL,
    sales_territory_name varchar(50) NOT NULL,
    sales_territory_sales_ytd DECIMAL(19,4) NOT NULL,
    sales_territory_sales_last_year DECIMAL(19,4) NOT NULL,
    sales_territory_cost_ytd DECIMAL(19,4) NOT NULL,
    sales_territory_cost_last_year DECIMAL(19,4) NOT NULL,

    /*country_region_customer*/
    country_region_currency_currency_code varchar(3) NOT NULL,
    country_region_currency_country_region_code varchar(3) NOT NULL,

    /*currency*/
    currency_code varchar(3) NOT NULL,
    currency_name varchar(255) NOT NULL,
 
    change_date TIMESTAMP,
);

CREATE TABLE work_order_routing(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,

    work_order_id INT NOT NULL,

     /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    scheduled_start_date date NOT NULL,
    scheduled_end_date date NOT NULL,
    actual_start_date date,
    actual_end_date date,
    start_date date NOT NULL,
    end_date date,
    due_date date NOT NULL,

    operations_sequence INT NOT NULL,
    actual_resource_hours DECIMAL(9,4),
    planned_cost DECIMAL NOT NULL,
    actual_cost DECIMAL,
    order_qty INT NOT NULL,
    stocked_qty INT NOT NULL,
    scrapped_qty INT NOT NULL,

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    /*scrap_reason*/
    scrap_reason_id INT,
    scrap_reason_name varchar(50),

    /*location*/
    location_id INT NOT NULL,
    availability DECIMAL(8,2) NOT NULL,
    cost_rate DECIMAL(8,2) NOT NULL,
    location_name varchar(50) NOT NULL,

    change_date TIMESTAMP,
)

CREATE TABLE purchase_order(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,

    purchase_order_id INT NOT NULL,
    purchase_order_detail_id INT NOT NULL,
    purchase_order_transaction_id INT NOT NULL,

    revision_number INT NOT NULL,
    status INT NOT NULL,
    order_qty INT NOT NULL,
    unit_price DECIMAL(18,4) NOT NULL,
    line_total DECIMAL(18,4) NOT NULL,
    received_qty DECIMAL(8,2) NOT NULL, 
    rejected_qty DECIMAL(8,2) NOT NULL,
    stocket_qty DECIMAL(8,2) NOT NULL,
    sub_total DECIMAL(18,4) NOT NULL,
    tax_amt DECIMAL(18,4) NOT NULL,
    freight DECIMAL(18,4) NOT NULL,
    total_due DECIMAL(18,4) NOT NULL,

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    /* Employee */
    employee_id varchar(255) NOT NULL,
    employee_full_name varchar(255) NOT NULL,
    employee_ss_number varchar(255),
    employee_phone_number varchar(255),
    employee_home_phone_number varchar(255),
    employee_extention varchar(255),
    employee_sales_YTD INT,
    employee_sales_last_year INT,
    employee_department_head varchar(255),
    employee_department varchar(255),
    employee_start_date date,
    employee_birth_date date,
    employee_salary DECIMAL(19,4),
    employee_country varchar(255),
    employee_region varchar(255),
    employee_city varchar(255),
    employee_zip_code varchar(255),
    employee_street_name varchar(255),
    employee_house_number varchar(10),
    employee_manager varchar(255),
    employee_health_insurance bit,
    employee_life_insurance bit,
    employee_day_care bit,
    employee_sex varchar(1),
    employee_termination_date date,
    employee_title varchar(255),
    employee_title_of_courtesy varchar(255),
    employee_group varchar(255),
    employee_territory varchar(255),
    employee_country_region_code varchar(255),
    employee_salaried_flag bit,
    employee_vactions_hours INT,
    employee_sick_leave_hours INT,
    employee_martial_status varchar(255),
    employee_orginanizion_level INT,
    employee_demographics varchar(255),
    employee_sales_quota INT,
    employee_bonus DECIMAL(19,4),
    employee_commission_pct DECIMAL(19,4),

    /*ship_method*/
    ship_method_name varchar(255) NOT NULL,
    ship_method_base DECIMAL(18,4) NOT NULL,
    ship_method_rate DECIMAL(18,4) NOT NULL,

    /*vendor*/
    vendor_business_entity_id varchar(255) NOT NULL,
    vendor_credit_rating INT NOT NULL,
    vendor_account_number varchar(15) NOT NULL,
    vendor_name varchar(50) NOT NULL,
    vendor_active_flag bit NOT NULL,
    vendor_purchasing_webservice_url varchar(1024),
    vendor_preferred_vendor_status bit NOT NULL,

    change_date TIMESTAMP,
)

CREATE TABLE price_history_shopping_cart(
    S_KEY INT IDENTITY(1,1) PRIMARY KEY,
    price_history_shopping_cart_product_id varchar(255) NOT NULL,
    price_history_shopping_cart_item_id INT NOT NULL,

    /* Date */
    year varchar(4) NOT NULL,
    quarter varchar(1) NOT NULL,
    month varchar(2) NOT NULL,
    day varchar(2) NOT NULL,
    hour varchar(2) NOT NULL,
    minute varchar(2) NOT NULL,
    start_date date NOT NULL,
    end_date date,

    price_history_shopping_cart_list_price DECIMAL(18,4) NOT NULL,
    price_history_shopping_cart_quantity INT NOT NULL,

    /* Product */
    product_id int NOT NULL,
    product_name varchar(max) NOT NULL,
    product_number varchar(255),
    product_make_flag INT,
    product_finished_goods_flag INT,
    product_safety_stock_level INT,
    product_reorder_point INT,
    product_standard_cost DECIMAL(19,4),
    product_list_price DECIMAL(19,4),
    product_size varchar(255),
    product_weight DECIMAL(19,4),
    product_days_to_manufacture INT,
    product_line varchar(255),
    product_class varchar(255),
    product_style varchar(255),
    product_category varchar(255),
    product_subcategory varchar(255),
    product_model varchar(255),
    product_sell_start_date date,
    product_sell_end_date date,
    product_discontinued_date date,
    product_discontinued bit NOT NULL,
    product_size_unit_measure_code varchar(255),
    product_weight_unit_measure_code varchar(255),
    product_vendor_country varchar(255),
    product_vendor_city varchar(255),
    product_vendor_postal_code varchar(255),
    product_vendor_address varchar(255),
    product_vendor_name varchar(255),
    product_color varchar(255),
    product_shelf INT,
    product_bin INT,
    product_quantity INT,

    change_date TIMESTAMP,
)